
BLENDER="C:\Program Files\Blender Foundation\Blender 4.2\blender.exe"
DIST=../dist

all : \
    $(DIST)/phone.pnct \
    $(DIST)/phone.scene \

$(DIST)/phone.scene :phone.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "phone.blend:Main" "$(DIST)/phone.scene"

$(DIST)/phone.pnct : phone.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "phone.blend:Main" "$(DIST)/phone.pnct" 
